
package ua.nure.film.service;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import ua.nure.film.entity.Film;
import ua.nure.film.entity.Ticket;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FilmService", targetNamespace = "http://film.nure.ua/service")
@XmlSeeAlso({
    ua.nure.film.entity.ObjectFactory.class,
    ua.nure.film.service.ObjectFactory.class
})
public interface FilmService {


    /**
     * 
     * @param film
     * @return
     *     returns int
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://film.nure.ua/entity")
    @RequestWrapper(localName = "addFilm", targetNamespace = "http://film.nure.ua/service", className = "ua.nure.film.service.AddFilm")
    @ResponseWrapper(localName = "addFilmResponse", targetNamespace = "http://film.nure.ua/service", className = "ua.nure.film.service.AddFilmResponse")
    @Action(input = "http://film.nure.ua/service/FilmService/addFilmRequest", output = "http://film.nure.ua/service/FilmService/addFilmResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://film.nure.ua/service/FilmService/addFilm/Fault/DAOException")
    })
    public int addFilm(
        @WebParam(name = "Film", targetNamespace = "http://film.nure.ua/entity")
        Film film)
        throws DAOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ua.nure.film.entity.Film>
     */
    @WebMethod
    @WebResult(name = "listFilms", targetNamespace = "http://film.nure.ua/entity")
    @RequestWrapper(localName = "listFilms", targetNamespace = "http://film.nure.ua/service", className = "ua.nure.film.service.ListFilms")
    @ResponseWrapper(localName = "listFilmsResponse", targetNamespace = "http://film.nure.ua/service", className = "ua.nure.film.service.ListFilmsResponse")
    @Action(input = "http://film.nure.ua/service/FilmService/listFilmsRequest", output = "http://film.nure.ua/service/FilmService/listFilmsResponse")
    public List<Film> listFilms();

    /**
     * 
     * @param ticket
     * @param filmId
     * @throws DAOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addTicket", targetNamespace = "http://film.nure.ua/service", className = "ua.nure.film.service.AddTicket")
    @ResponseWrapper(localName = "addTicketResponse", targetNamespace = "http://film.nure.ua/service", className = "ua.nure.film.service.AddTicketResponse")
    @Action(input = "http://film.nure.ua/service/FilmService/addTicketRequest", output = "http://film.nure.ua/service/FilmService/addTicketResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://film.nure.ua/service/FilmService/addTicket/Fault/DAOException")
    })
    public void addTicket(
        @WebParam(name = "filmId", targetNamespace = "")
        int filmId,
        @WebParam(name = "Ticket", targetNamespace = "http://film.nure.ua/entity")
        Ticket ticket)
        throws DAOException_Exception
    ;

    /**
     * 
     * @param ticketNumber
     * @return
     *     returns ua.nure.film.entity.Ticket
     */
    @WebMethod
    @WebResult(name = "Ticket", targetNamespace = "http://film.nure.ua/entity")
    @RequestWrapper(localName = "getTicket", targetNamespace = "http://film.nure.ua/service", className = "ua.nure.film.service.GetTicket")
    @ResponseWrapper(localName = "getTicketResponse", targetNamespace = "http://film.nure.ua/service", className = "ua.nure.film.service.GetTicketResponse")
    @Action(input = "http://film.nure.ua/service/FilmService/getTicketRequest", output = "http://film.nure.ua/service/FilmService/getTicketResponse")
    public Ticket getTicket(
        @WebParam(name = "ticketNumber", targetNamespace = "")
        String ticketNumber);

    /**
     * 
     * @param filmId
     * @throws DAOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeFilm", targetNamespace = "http://film.nure.ua/service", className = "ua.nure.film.service.RemoveFilm")
    @ResponseWrapper(localName = "removeFilmResponse", targetNamespace = "http://film.nure.ua/service", className = "ua.nure.film.service.RemoveFilmResponse")
    @Action(input = "http://film.nure.ua/service/FilmService/removeFilmRequest", output = "http://film.nure.ua/service/FilmService/removeFilmResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://film.nure.ua/service/FilmService/removeFilm/Fault/DAOException")
    })
    public void removeFilm(
        @WebParam(name = "filmId", targetNamespace = "")
        int filmId)
        throws DAOException_Exception
    ;

}
