//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.14 at 09:46:54 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/xml/entity/cinema/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.xml.entity.cinema;
